"""Security policy helpers for shell tool execution."""

from __future__ import annotations

import json
import re
import shlex
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..redaction import redact_data


@dataclass
class CommandSecurityDecision:
    """Result of a command security check."""

    allowed: bool
    reason: str = ""
    risk_level: str = "low"
    matched_rules: list[str] = field(default_factory=list)
    requires_confirmation: bool = False


@dataclass
class BashSecurityPolicy:
    """Static safety checks for commands generated by an agent."""

    enabled: bool = True
    allowed_commands: list[str] = field(default_factory=list)
    blocked_commands: list[str] = field(
        default_factory=lambda: [
            "rm",
            "del",
            "erase",
            "format",
            "shutdown",
            "reboot",
            "restart-computer",
            "stop-computer",
            "mkfs",
            "dd",
            "diskpart",
            "reg",
            "set-executionpolicy",
        ]
    )
    allow_outside_workspace: bool = False
    audit_enabled: bool = True
    audit_log_path: str | None = None


_SHELL_SEPARATORS = re.compile(r"\s*(?:&&|\|\||;|\||&)\s*")
_WINDOWS_ABS_PATH = re.compile(r"(?<![\w])(?:[A-Za-z]:[\\/][^\s\"'`;|&<>]*)")
_UNIX_ABS_PATH = re.compile(r"(?<![\w.-])/(?:[^\s\"'`;|&<>]+)")
_DANGEROUS_PATTERNS: list[tuple[str, str]] = [
    ("recursive_force_delete", r"\brm\s+[^;&|]*-[^\s;&|]*r[^\s;&|]*f|\brm\s+[^;&|]*-[^\s;&|]*f[^\s;&|]*r"),
    ("remove_item_recursive_force", r"\bRemove-Item\b[^;&|]*(?:-Recurse\b[^;&|]*-Force|-Force\b[^;&|]*-Recurse)"),
    ("delete_all", r"\b(?:del|erase)\b[^;&|]*(?:/s|/q|\\\*|\*)"),
    ("format_disk", r"\bformat\b\s+[A-Za-z]:"),
    ("disk_wipe", r"\b(?:mkfs|dd|diskpart)\b"),
    ("system_shutdown", r"\b(?:shutdown|reboot|Restart-Computer|Stop-Computer)\b"),
    ("powershell_policy_change", r"\bSet-ExecutionPolicy\b"),
]
_CONFIRMATION_PATTERNS: list[tuple[str, str]] = [
    ("package_install:pip", r"\bpip(?:3)?\s+install\b"),
    ("package_install:pipx", r"\bpipx\s+install\b"),
    ("package_change:uv_add", r"\buv\s+add\b"),
    ("package_change:uv_sync", r"\buv\s+sync\b"),
    ("package_install:npm", r"\bnpm\s+install\b"),
    ("package_install:pnpm", r"\bpnpm\s+install\b"),
    ("package_install:yarn", r"\byarn\s+add\b"),
    ("network_download:curl", r"\bcurl\b"),
    ("network_download:wget", r"\bwget\b"),
    ("network_download:powershell", r"\b(?:Invoke-WebRequest|iwr)\b"),
    ("git_write:commit", r"\bgit\s+commit\b"),
    ("git_write:push", r"\bgit\s+push\b"),
    ("git_write:pull", r"\bgit\s+pull\b"),
    ("git_write:reset", r"\bgit\s+reset\b"),
    ("git_write:clean", r"\bgit\s+clean\b"),
    ("git_write:checkout", r"\bgit\s+checkout\b"),
    ("git_write:merge", r"\bgit\s+merge\b"),
    ("git_write:rebase", r"\bgit\s+rebase\b"),
    ("subshell:powershell", r"^\s*powershell(?:\.exe)?\b"),
    ("subshell:pwsh", r"^\s*pwsh(?:\.exe)?\b"),
    ("subshell:cmd", r"^\s*cmd(?:\.exe)?\b"),
    ("subshell:bash", r"^\s*bash\b"),
    ("subshell:sh", r"^\s*sh\b"),
]


@dataclass(frozen=True)
class CommandSegment:
    """One simple shell command segment after lightweight parsing."""

    head: str
    args: list[str]


def _strip_shell_quotes(token: str) -> str:
    return token.strip().strip("\"'")


def _split_command_segments(command: str) -> list[str]:
    """Split a shell command on separators while respecting simple quotes."""

    segments: list[str] = []
    current: list[str] = []
    quote: str | None = None
    i = 0

    while i < len(command):
        char = command[i]

        if char in {"'", '"'}:
            quote = None if quote == char else char if quote is None else quote
            current.append(char)
            i += 1
            continue

        if quote is None:
            two_char = command[i : i + 2]
            if two_char in {"&&", "||"}:
                segment = "".join(current).strip()
                if segment:
                    segments.append(segment)
                current = []
                i += 2
                continue
            if char in {";", "|", "&"}:
                segment = "".join(current).strip()
                if segment:
                    segments.append(segment)
                current = []
                i += 1
                continue

        current.append(char)
        i += 1

    segment = "".join(current).strip()
    if segment:
        segments.append(segment)
    return segments


def _parse_command_segments(command: str) -> list[CommandSegment]:
    """Return structured command segments using shell-like tokenization."""

    parsed: list[CommandSegment] = []
    for segment in _split_command_segments(command):
        try:
            tokens = shlex.split(segment, posix=True)
        except ValueError:
            tokens = segment.split()

        if not tokens:
            continue

        head = Path(_strip_shell_quotes(tokens[0])).name.lower()
        args = [_strip_shell_quotes(token) for token in tokens[1:]]
        if head:
            parsed.append(CommandSegment(head=head, args=args))
    return parsed


def _command_heads(command: str) -> list[str]:
    """Return the first token for each simple command segment."""

    return [segment.head for segment in _parse_command_segments(command)]


def _structured_dangerous_rules(segments: list[CommandSegment]) -> list[str]:
    """Detect dangerous commands from parsed command heads and arguments."""

    matched_rules: list[str] = []
    for segment in segments:
        args_lower = [arg.lower() for arg in segment.args]
        option_text = " ".join(arg for arg in args_lower if arg.startswith("-") or arg.startswith("/"))

        if segment.head == "rm" and "r" in option_text and "f" in option_text:
            matched_rules.append("recursive_force_delete")
        elif segment.head == "remove-item" and "-recurse" in args_lower and "-force" in args_lower:
            matched_rules.append("remove_item_recursive_force")
        elif segment.head in {"del", "erase"} and (
            any(arg in {"/s", "/q"} for arg in args_lower) or any("*" in arg for arg in segment.args)
        ):
            matched_rules.append("delete_all")
        elif segment.head == "format" and any(re.match(r"^[A-Za-z]:$", arg) for arg in segment.args):
            matched_rules.append("format_disk")
        elif segment.head in {"mkfs", "dd", "diskpart"}:
            matched_rules.append("disk_wipe")
        elif segment.head in {"shutdown", "reboot", "restart-computer", "stop-computer"}:
            matched_rules.append("system_shutdown")
        elif segment.head == "set-executionpolicy":
            matched_rules.append("powershell_policy_change")

    return matched_rules


def _is_subpath(path: Path, parent: Path) -> bool:
    try:
        path.resolve(strict=False).relative_to(parent.resolve(strict=False))
        return True
    except ValueError:
        return False


def _extract_absolute_paths(command: str) -> list[str]:
    paths = _WINDOWS_ABS_PATH.findall(command)
    paths.extend(_UNIX_ABS_PATH.findall(command))
    return paths


def check_command_security(
    command: str,
    workspace_dir: str | None,
    policy: BashSecurityPolicy | None = None,
) -> CommandSecurityDecision:
    """Validate a shell command before execution."""

    policy = policy or BashSecurityPolicy()
    if not policy.enabled:
        return CommandSecurityDecision(allowed=True, reason="security policy disabled")

    matched_rules: list[str] = []
    command_segments = _parse_command_segments(command)
    command_heads = [segment.head for segment in command_segments]
    blocked = {cmd.lower() for cmd in policy.blocked_commands}
    allowed = {cmd.lower() for cmd in policy.allowed_commands}

    if allowed:
        disallowed_heads = [head for head in command_heads if head and head not in allowed]
        if disallowed_heads:
            return CommandSecurityDecision(
                allowed=False,
                reason=f"command not in allowlist: {', '.join(sorted(set(disallowed_heads)))}",
                risk_level="medium",
                matched_rules=["allowlist"],
            )

    blocked_heads = [head for head in command_heads if head in blocked]
    if blocked_heads:
        matched_rules.append(f"blocked_command:{','.join(sorted(set(blocked_heads)))}")

    matched_rules.extend(_structured_dangerous_rules(command_segments))

    for rule_name, pattern in _DANGEROUS_PATTERNS:
        if re.search(pattern, command, flags=re.IGNORECASE):
            matched_rules.append(rule_name)

    matched_rules = list(dict.fromkeys(matched_rules))

    if matched_rules:
        return CommandSecurityDecision(
            allowed=False,
            reason=f"blocked risky command pattern: {', '.join(matched_rules)}",
            risk_level="high",
            matched_rules=matched_rules,
        )

    if workspace_dir and not policy.allow_outside_workspace:
        workspace = Path(workspace_dir)
        outside_paths: list[str] = []
        for raw_path in _extract_absolute_paths(command):
            candidate = Path(raw_path)
            if not _is_subpath(candidate, workspace):
                outside_paths.append(raw_path)

        if outside_paths:
            return CommandSecurityDecision(
                allowed=False,
                reason=f"absolute path outside workspace: {', '.join(sorted(set(outside_paths)))}",
                risk_level="high",
                matched_rules=["outside_workspace"],
            )

    return CommandSecurityDecision(allowed=True, reason="command passed security checks")


def requires_bash_confirmation(command: str, run_in_background: bool = False) -> CommandSecurityDecision:
    """Return a confirmation decision for medium-risk bash commands."""

    matched_rules: list[str] = []
    if run_in_background:
        matched_rules.append("background_execution")

    for rule_name, pattern in _CONFIRMATION_PATTERNS:
        if re.search(pattern, command, flags=re.IGNORECASE):
            matched_rules.append(rule_name)

    if not matched_rules:
        return CommandSecurityDecision(allowed=True, reason="command does not require confirmation")

    return CommandSecurityDecision(
        allowed=True,
        reason=f"command requires user confirmation: {', '.join(matched_rules)}",
        risk_level="medium",
        matched_rules=matched_rules,
        requires_confirmation=True,
    )


def default_audit_log_path(workspace_dir: str | None) -> Path:
    """Return the default JSONL audit log path."""

    base_dir = Path(workspace_dir) if workspace_dir else Path.cwd()
    return base_dir / ".mini_agent" / "bash_audit.jsonl"


def write_bash_audit_event(
    event: dict[str, Any],
    workspace_dir: str | None,
    policy: BashSecurityPolicy | None = None,
) -> None:
    """Append one shell audit event as JSON Lines."""

    policy = policy or BashSecurityPolicy()
    if not policy.audit_enabled:
        return

    log_path = Path(policy.audit_log_path) if policy.audit_log_path else default_audit_log_path(workspace_dir)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        **redact_data(event),
    }
    with log_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")
